### ISSUE TITLE
Polkabridge

### ISSUE THREAD

**Issue by pmantz** [polkadot-js/phishing#116]
You have been redirected because the Polkadot{.js} extension believes that this website could compromise the security of your accounts and your tokens.

https://polkabridge.org/

Note that this website was reported on a community-driven, curated list. It might be incomplete or inaccurate. If you think that this website was flagged incorrectly, please open an issue by clicking here.

is this a valid warning?

**Comment by jacogr** [comment]
Ao let me preface this with the fact that there could very well be false positives. Some are very clear cut attempts to do users harms and other may be perceived as such and are not. Basically the list will always aims to be overly cautious since the ocean has a lot of sharks - but it could mean a dolphin is caught in the net. 

There has been multiple warnings against the site received across Discord, Telegram and Reddit. These are all based on a number of perceived red flags, including -

- listing as a Substrate project (it does not build on Substrate/Rust), 
- having no GH activity (apart from templates that are not updated), 
- partnerships that does not exist (Polkadot and Moonbeam), 
- a pure price-only, non-technology focus,
- sites with stock photos. (On the last one I can appreciate people wanting to stay anonymous for various reasons)

The idea is not to play judge and jury (unless clear-cut), but due to the number of reports based on some parts of the above it was listed. 

Certainly wish developers all the best with their projects, and if this is a mistaken listing (as per the first paragraph) it can be removed.
