### ISSUE TITLE
PolkaBridge website was flagged incorrectly

### ISSUE THREAD

**Issue by zephwilliams** [polkadot-js/phishing#118]
Hi, I'm Zeph Williams, Co-founder of PolkaBridge.

I found PolkaBridge website was flagged incorrectly. So I open this issue. I think the reason was that there has been multiple warnings against the site received across Discord, Telegram and Reddit. I understand, but I think this will happen for every projects.

- PBR did not build on Substrate, yes for now. But I'm sure in future and it will be fully audited by the 3rd party.
- We didn't have partnership with Polkadot, yes and we haven't ever said that. But our products will be built and developed with Polkadot in center.
- Our team was anonymous because we had plan to reveal after migrating PBR token to Polkadot parachain. And we said that multiple times.

So I think this is a misconceive. Please check and remove the flag on PolkaBridge website please. Thank you.

Best Regards
Zeph Williams

**Comment by jacogr** [comment]
Thanks fo the report. Like I mentioned in #116,there will probably be some false positives since there a lot of scams out there. Having said that, the listing was not done lightly, since there is a flood of reports for a number of channels. Hopefully that gets cleared out and doesn't continue pouring in.

Removed the listing in the linked PR.

**Comment by zephwilliams** [comment]
> Thanks fo the report. Like I mentioned in #116, there will probably be some false positives since there a lot of scams out there. Having said that, the listing was not done lightly, since there is a flood of reports for a number of channels. Hopefully that gets cleared out and doesn't continue pouring in.
> 
> Removed the listing in the linked PR.

So excited to receive your friendly reply. Thanks so much.

**Comment by jimoquinn** [comment]
"So excited to receive your friendly reply. Thanks so much."

This is a not so friendly reply, Mr. "Williams".

I would like to request their website be added to back to the phishing list.  These 2 anonymous founders have committed several egregious, if not illegal, offenses:  

*  Burned tokens in holder's wallets -- they gave users 2 weeks to migrate tokens.  I did not receive this notice nor did roughly 20% of all PBR token holders, because then in a baffling move, they decided to burn millions of dollars worth of tokens sitting in holder's wallets.  One day I checked my Ledger and the tokens were worth $0.  Gone, destroyed, worthless.  They refuse to make whole any wallets that were burned and I've yet to receive an explanation as to why they destroyed my tokens.  This is exactly why anonymous teams are terrible for the entire crypto ecosystem, they duck accountability, and continue on with little consequence.  Evidence:  I have curated a list of individuals, that is growing daily, who will gladly provide wallet addresses as evidence.  
* CertiK audit - the audit found 4 Major Issues, one which was a Major Security Issue.  It was suggested they implement a timelock or multisig to prevent abuse of funds, but this recommendation was ignored as evidenced by their code in github and the report from CertiK.  In addition, they have over 12 smart contracts in production that have yet to undergo audit.  This is not only disingenuous, but dangerous given their reckless and costly behavior with holders tokens.  Evidence:  CertiK report, page 7:  https://www.certik.org/projects/polkabridge
* Riding on the Polkadot goodwill & brand - they have painted their entire operation in Polkadot colors, brand, and and style.  They are bold with the "Powered by Polkadot" logo on their homepage, which is clearly a lie, because not one line of code in their github uses anything from Polkadot ecosystem.  I was fooled, as were others, because I see the chatter on their telegram channels, reddit, twitter, where people are asking if they are part of Polkadot.  The Polkadot brand is distinct so their adopting it was no mistake, it was intentional.  Consequently, they are tarnishing your goodwill.  Evidence:  https://imgur.com/RP33k2f


Please consider adding the Polkabridge.org website back on the phishing list.
