### ISSUE TITLE
scam  from same scammers

### ISSUE THREAD

**Issue by cooldude78** [polkadot-js/phishing#1611]
https://tron-trx.events/airdrop/verification/

**Comment by dubstard** [comment]
Those actors rented a 15 dollar VPS and keep reusing it haha, EZ block many targets


apart from `tron-trx.events`
they also have 

```
stepn-activity.live
myneighboralice.events
avax-event.live
cardano-ada.events
terra-luna.events
```
All of which are exactly the same scam, send 1X and get 3X, which has been going on since pre 2017, and still manages to lure victims, how is that possible is beyond me.

**Comment by cooldude78** [comment]
they use the stolen money to fund their annual summer holidays with coke and hookers
