### ISSUE TITLE
re: dot 3x on telegram polkadot events

### ISSUE THREAD

**Issue by tannertanner1** [polkadot-js/phishing#72]
hey, polkadot{.js} detected phishing for https://t.me/c/1371228565/18396

https://polkadotlive.network/
https://polkadotlive.network/block-assets/index.html

**Comment by jacogr** [comment]
@Tbaut Can you take a look at this one please in the extension. It is on the blocklist, but in some way it gets somewhat bypassed. So what happens when I click it is that the extension blocks, but the page opens a new tab anyway. So you end up with the blocked tab and then a new tab on this page.

Would need a work-around here, they seem to use something to get around the extension.

**Comment by tannertanner1** [comment]
seems like a scam, if you could confirm, would be great! thanks!

**Comment by jacogr** [comment]
It is a scam :)

**Comment by tannertanner1** [comment]
so is dot only on discord, not telegram?

**Comment by jacogr** [comment]
No, there are official channels (and unofficial ones) everywhere - however in this case it is a clear scam. It was first reported on 19 Jan. 

There are NO DOT airdrops ongoing, nor planned anytime into the future. If plans do change on the network, there will be ab announcement on the official https://polkadot.network page.

**Comment by tannertanner1** [comment]
thanks:)

**Comment by jackesky** [comment]
> @tannertanner1 Thanks for logging.
> 
> @Tbaut Can you take a look at this one please in the extension. It is on the blocklist, but in some way it gets bypassed.
> 
> So what happens when I click it is that the extension blocks, but the page opens a new tab anyway. So you end up with the blocked tab and then a new tab on this page.
> 
> Would need a work-around here, they seem to use something to get around the extension.

Its a cell phone mobile issue, I have noticed

**Comment by GenOtter** [comment]
I followed the 3x DOT scam through the blockchain
Some seems to go here: 13wj7TPehUG1stdyWouo4nZVai39rARmz2RGB1MTs22qgVCm
Which is then immediately sent to: 14oEqqqCabUQdsdq1zP1qdb8b4uhEnc2mL1YYHKf8xYbh8FB
And finally ends up here: 1exaAg2VJRQbyUBAeXcktChCAqjVP9TUxF3zo23R2T6EGdE

When you search this final address, you find it's the 20th largest wallet on the network, with 8.7 million DOT.
Trying to find it's origin. But I noticed it dumped 350,000 DOT to 0x1c3b9d3ce0630c922e67ea0f5883613877b5172db47cd8c159c05f75d55d04ed

Unfortunately that's where my search ended, because I can't view the wallet.

**Comment by GenOtter** [comment]
![image_2021-02-08_17-22-26](https://user-images.githubusercontent.com/78031724/107257124-43014d80-6a32-11eb-9aec-ed41f5cb1a4e.png)

**Comment by GenOtter** [comment]
![399,999](https://user-images.githubusercontent.com/78031724/107257314-7348ec00-6a32-11eb-9153-ec91d82a60c9.png)

**Comment by jacogr** [comment]
The final is the Binance address (sadly blocked that one befor, not quite such a good idea). will check the rest, thank you.

**Comment by jackesky** [comment]
> The final ` 1exa...` is the Binance address (I sadly blocked that one before, which is not quite such a good idea :). Will check the rest, thank you.

Has some one at Web3 contacted Binance directly requesting they block scam victoms from sending their dot into that Binance address ¿

Perhaps contacting the exchanges direct to block any user on their platform sending dot into those addresses on regualar basis is one short term possibility¿

**Comment by jackesky** [comment]
does that mean its moved into a generic Binance address for selling on
their exchange or into the wallet of the actual scammer?

**Comment by jacogr** [comment]
They moved it to Binance to sell.

**Comment by jackesky** [comment]
In some good news one Dot holder questioned why a phishing link was showing
up in one of the scam dot groups. The fake admin using the name Urban said
"their tec" would look into it. Some of them know the net is closing in.
Now we just need someone to tell Bianance ( and other exchanges) of the
Phishing links and keep them updated so they can black list the addresses.
I would be happy to help with that.
.

**Comment by jacogr** [comment]
At least one person saved. Well, on their side they probably changed the address, so the game of whack-a-mole continues...

**Comment by jacogr** [comment]
Closing this. The current version of the extension now correctly detects links opened in a new tab. (Previously it was only in the current window). Additionally, as mentioned, the addresses are on the list.
